---
services:
  swincebot:
    build:
      context: .
      dockerfile: ./resources/Dockerfile
    ports: [1157:1157]
    environment:
      - LOG_LEVEL=debug
      - LOG_FORMAT=json
      - LOG_OUTPUT=stdout
      - LISTEN_PORT=6969
      - DATABASE_PATH=/var/run/store.db
      - GRACEFUL_TIMEOUT=200ms
      - SECRETS_PATH=/etc/secrets
    volumes: [./.runtime:/var/run, ./.secrets:/etc/secrets]
